
CC			=	gcc

SRCS		=	ft_memset.c ft_bzero.c ft_memcpy.c \
		  		ft_memccpy.c ft_memmove.c ft_memchr.c \
		  		ft_memcmp.c ft_strlen.c ft_strlcpy.c \
		  		ft_strlcat.c ft_strchr.c ft_strrchr.c \
		  		ft_strnstr.c ft_strncmp.c ft_atoi.c \
		  		ft_isalpha.c ft_isdigit.c ft_isalnum.c \
		  		ft_isascii.c ft_isprint.c ft_toupper.c \
		  		ft_tolower.c ft_calloc.c ft_strdup.c \
		  		ft_substr.c ft_strjoin.c ft_strtrim.c \
		  		ft_split.c ft_itoa.c ft_strmapi.c \
		  		ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c \
		  		ft_putnbr_fd.c

SRCS_BNS	=	ft_lstnew.c ft_lstadd_front.c ft_lstsize.c \
				ft_lstlast.c ft_lstadd_back.c ft_lstdelone.c \
				ft_lstclear.c ft_lstiter.c ft_lstmap.c

OBJS		=	$(SRCS:.c=.o)

OBJS_BNS	=	$(SRCS_BNS:.c=.o)

NAME	= libft.a

CFLAGS	= -Wall -Wextra -Werror

RM		= rm -f

.c.o:
			$(CC) $(CFLAGS) -c $< -o ${<:.c=.o}

$(NAME):	$(OBJS)
			ar cr $(NAME) $(OBJS)
			ranlib $(NAME)

all:		$(NAME)

bonus:		$(OBJS) $(OBJS_BNS)
			ar cr $(NAME) $(OBJS) $(OBJS_BNS)
			ranlib $(NAME)

clean:
			$(RM) $(OBJS) $(OBJS_BNS)

fclean:		clean
			$(RM) $(NAME)

re:			fclean all

.PHONY:		all clean fclean bonus re
